### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by krichter722** [noloader/Build-Scripts#1]
I'd like to see a CI setup for Build-Scripts which seems to be a sophisticated project. I personally like Travis CI for the github.com integration and speed, but recently prefer GitLab CI which uses Docker images that are quite empty and allow to detect more issues than Travis CI as well as test an almost arbitrary amount of Linux OS (and maybe more - I'm not that much familiar with docker/virtualization) and one can use a local runner to test for hours for free.

I'm willing to provide a GitLab CI script as far as I get if you have any interest in that and are ready to mirror to gitlab.com.

**Comment by noloader** [comment]
@krichter722,

A CI setup would probably be a good idea. For my other projects I use Travis, but I know some folks prefer something else. For example, I collaborate with [Crypto++](https://www.cryptopp.com/), and [Travis is used there](https://github.com/weidai11/cryptopp/blob/master/.travis.yml).

I think I prefer to avoid GitLab. Are you able to clone from GitHub to GitLab? If so, that seems like a way to allow you to hit your GitLab goal while keep the upstream sources at GitHub. When needed, you just do a `git pull upstream master` to pull from GitHub, and then `git push` to push them to the GitLab clone.

If you want to try GitHub and Travis, then it should be as simple as these items to hit the high points. Don't worry, it builds a lot of stuff (the scripts were designed to be easy to use for stuff like this):

```
./build-cacerts.sh

INSTX_PREFIX=/tmp ./build-wget.sh

INSTX_PREFIX=/tmp ./build-ssh.sh

INSTX_PREFIX=/tmp ./build-git.sh
```

You are still welcomed to work here. I'd like to see how you would handle a new program or library. Can you take a shot at adding a Python 2.7 build script. I actually have a need for it on Fedora 10, but I have not gotten around to writing it.

I would start by `cp build-ssh.sh build-python2.sh`. Then, start hacking away. The first thing to do is change the internal names from SSH to PYTHON. Then, download Python 2 and run `./configure --help` to see what options it needs to make it featured. I expect to see the usual suspects, like `libidn` and OpenSSL.

Once you are complete make a pull request.

**Comment by krichter722** [comment]
@noloader I started a GitLab CI script (without wanting to push you towards officially mirroring to gitlab.com) and noticed right at the beginning that I don't seem to figure out the dependency loop between `build-cacerts.sh` and `build-git.sh` and `build-wget.sh`

```

********** GlobalSign Root R1 **********

Wrote /root/.cacert/globalsign-root-r1.pem

********** Let's Encrypt Root **********

Wrote /root/.cacert/lets-encrypt-root-x3.pem

********** identrust Root **********

Wrote /root/.cacert/identrust-root-x3.pem

********** DigiTrust Root **********

Wrote /root/.cacert/digitrust-root-ca.pem

********** DigiCert Root **********

Wrote /root/.cacert/digicert-root-ca.pem

********** AddTrust Root CA **********

Wrote /root/.cacert/addtrust-root-ca.pem

********** cURL CA-Certs **********

./build-cacert.sh: line 243: wget: command not found
./build-cacert.sh: line 244: git: command not found
Downloaded /root/.cacert/cacert.pem

Some packages require Autotools. Please install autoconf, automake and libtool.
```
and
```
running ./build-git.sh
Some packages require several CA roots. Please run build-cacert.sh.
Failed to set environment
```
I assume that there's no solution and that `git` and `wget` or `ca-certifcates` need to be provided temporarily by the system package manager for the build of one script and then removed, but I wanted to have your feedback on that.

You can inspect the result of the first attempt of a CI script at https://gitlab.com/krichter/Build-Scripts/pipelines/18002068. What OS (in the form of a Docker image) would you like to see tested?

**Comment by noloader** [comment]
@krichter722,

Yeah, the scripts depend on an old version of Wget and Git. All systems I test on have them. I wonder why the CI machines don't have them.

Do you know if the machines have cURL available? We can probably switch to cuRL. In fact, I almost switched to cURL when building Wget.

**Comment by noloader** [comment]
@krichter722,

I sent you a Collaborator request. I think its good to have a few of them on a project.

Usually the work is nothing more than bumping version numbers when new versions of software is released. Feel free to bump and check-in as required.

**Comment by krichter722** [comment]
> Yeah, the scripts depend on an old version of Wget and Git. All systems I test on have them. I wonder why the CI machines don't have them.
>
> Do you know if the machines have cURL available? We can probably switch to cuRL. In fact, I almost switched to cURL when building Wget.

That's intended. The docker images are as empty as possible in order to be able to track any issues caused by dependencies which are provided on one system, but not the other (including helpful feedback in case of failure). The programs can simply be provided with the system package manager (`apt-get`, `yum`, etc.) and if you ever want to save those 2 seconds you can build your own Docker image with exactly the things you want to be there for CI tests (~3 hours to go through the tutorial).

I accepted your invitation, thank you.
