### ISSUE TITLE
Remove OpenSSL 1.0.2

### ISSUE THREAD

**Issue by noloader** [noloader/Build-Scripts#11]
OpenSSL 1.0.2 is now end of life. It needs to be removed in favor of something from the OpenSSL 1.1.x branch.

This could be painful.

**Comment by cswoodruff** [comment]
Is the plan to update the repo to deal with all the fallout from this change in OpenSSL? I'm seeing an error trying to build OpenSSL with this update now that it relies on `perl v5.10.0`. Building perl is also failing in #12. FYI, my goal is to build Git and OpenSSH on Centos 5 so that I can connect to Github with updated crypto keys. The old versions of git/ssh result in the following error for git pull/push commands.
```no kex alg
fatal: Could not read from remote repository.
```
Here is the log output from the build attempt of OpenSSL. 
```
$ ./build-openssl.sh 

Common flags and options:

  INSTX_BITNESS: 32-bits
   INSTX_PREFIX: /usr/local
   INSTX_LIBDIR: /usr/local/lib
    INSTX_RPATH: '$$ORIGIN/../lib'

PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
       CPPFLAGS: -I/usr/local/include -DNDEBUG
         CFLAGS: -g2 -O2 -fPIC -pthread
       CXXFLAGS: -g2 -O2 -fPIC -pthread
        LDFLAGS: -L/usr/local/lib -Wl,-R,'$$ORIGIN/../lib' -Wl,-R,/usr/local/lib -Wl,--enable-new-dtags
         LDLIBS: -ldl -lpthread

 WGET: /usr/local/bin/wget
 SH_CACERT_PATH: /usr/local/etc/pki
 SH_CACERT_FILE: /usr/local/etc/pki/cacert.pem

If you enter a sudo password, then it will be used for installation.
If you don't enter a password, then ensure INSTX_PREFIX is writable.
To avoid sudo and the password, just press ENTER and they won't be used.
Please enter password for sudo: 

OpenSSL requires Perl's Text::Template. Skipping OpenSSL self tests.
To fix this issue, please install Text-Template.

zlib is already installed.

********** OpenSSL **********

--2020-01-27 13:41:02--  https://www.openssl.org/source/openssl-1.1.1d.tar.gz
Resolving www.openssl.org (www.openssl.org)... 104.86.226.58, 2600:1406:3:39b::c1e, 2600:1406:3:38b::c1e
Connecting to www.openssl.org (www.openssl.org)|104.86.226.58|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8845861 (8.4M) [application/x-gzip]
Saving to: ‘openssl-1.1.1d.tar.gz’

openssl-1.1.1d.tar.gz         100%[===============================================>]   8.44M  12.1MB/s    in 0.7s    

2020-01-27 13:41:03 (12.1 MB/s) - ‘openssl-1.1.1d.tar.gz’ saved [8845861/8845861]

Patching Makefiles...
Operating system: i686-whatever-linux2
Perl v5.10.0 required--this is only v5.8.8, stopped at ./Configure line 12.
BEGIN failed--compilation aborted at ./Configure line 12.
Perl v5.10.0 required--this is only v5.8.8, stopped at ./Configure line 12.
BEGIN failed--compilation aborted at ./Configure line 12.
This system (linux-x86) is not supported. See file INSTALL for details.
Failed to configure OpenSSL
```

**Comment by noloader** [comment]
> Is the plan to update the repo to deal with all the fallout from this change in OpenSSL?

Yes.

I'm feeling some of your pain while testing on Ubuntu 4. There's an updated `setup-wget.sh` that includes Perl 5.10.1 so OpenSSL 1.1.x can work. With the bootstrapped Perl we at least get to a bootstrapped Wget. Now we can download stuff.

I'm getting ready to see what we can do for the regular OpenSSL that will be installed `/usr/local`. I hope we can build the latest Perl. I'm not a big fan of EOL'd Perl with security vulnerabilities.

**Comment by noloader** [comment]
It looks like we worked out the wrinkles of the OpenSSL 1.1.x migration. I was able to test back to Fedora 1 and Ubuntu 4.

Closing.
