### ISSUE TITLE
Nettle fails to build

### ISSUE THREAD

**Issue by sebsto** [noloader/Build-Scripts#3]
I am trying to build GNUTLS on Ubuntu. I receive an error while building the dependency `nettle`

```
sec_powm.c:293: GNU MP assertion failed: enb >= windowsize
Aborted (core dumped)
FAIL: rsa-compute-root
...
====================
1 of 98 tests failed
====================
Makefile:140: recipe for target 'check' failed
make[1]: *** [check] Error 1
make[1]: Leaving directory '/home/ubuntu/gnutls/Build-Scripts/nettle-3.4.1/testsuite'
Makefile:49: recipe for target 'check' failed
make: *** [check] Error 2
Failed to test Nettle
Failed to build Nettle
```

```
# uname -a
Linux ip-172-31-16-177 4.15.0-1033-aws #35-Ubuntu SMP Wed Feb 6 13:29:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by noloader** [comment]
Yeah, I think that needs [Commit 1f5b9812dec0](https://git.lysator.liu.se/nettle/nettle/commit/1f5b9812dec0). Let me see if Neils released a new version of the library.

**Comment by noloader** [comment]
This should clear the issue: [Commit 99f9085e2530](https://github.com/noloader/Build-Scripts/commit/99f9085e2530). When Neils releases a new Nettle version we should be able to drop the patch.

**Comment by sebsto** [comment]
Thanks - works now.
