### ISSUE TITLE
Guile fails to build on Ubuntu

### ISSUE THREAD

**Issue by sebsto** [noloader/Build-Scripts#5]
When trying to build `guile` on Ubuntu, I received the following error due to misisng dependencies 

```
checking for bdw-gc >= 7.2... no
configure: error: Package requirements (bdw-gc >= 7.2) were not met:

No package 'bdw-gc' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BDW_GC_CFLAGS
and BDW_GC_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Failed to configure Guile
```

```
# uname -a
Linux ip-172-31-16-177 4.15.0-1033-aws #35-Ubuntu SMP Wed Feb 6 13:29:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by noloader** [comment]
You have to install it from the distro. The Boehm GC is too hard to build correctly from scripts. It is more than simple configuration. For Boehm GC the right version has to be downloaded, too.

**Comment by sebsto** [comment]
Thanks.  
`apt-get install libgc-dev` did the trick.  Thanks for having updated the README

**Comment by noloader** [comment]
Your next problem will be with GnuTLS 3.6.6 not finding Guile 2.2.4. I already opened a bug report for it.

The confirmation email said it was assigned [Issue 726](https://gitlab.com/gnutls/gnutls/issues/726). But the bug report has not posted to GitLab yet.
