### ISSUE TITLE
Reset repository to one commit

### ISSUE THREAD

**Issue by noloader** [noloader/Build-Scripts#8]
I did a checkout to build a zip for an old Ubuntu machine. The clone and checkout takes too much time. A lot of the problem is the tarballs in `bootstrap/`. The history of the binary files waste too much time and storage. I only the need the latest state of sources that "just works". I don't care about last week's version of a script or tarball.

To reduce the number and size of objects in history the repository will be reset according to [git-clearHistory](https://gist.github.com/stephenhardy/5470814).

**Comment by noloader** [comment]
Completed at [Commit 0eebdc1ce22f](https://github.com/noloader/Build-Scripts/commit/0eebdc1ce22f).

**Comment by krichter722** [comment]
This is typically solved by providing release archives which include all relevant files, usually all files except the SCM files.

**Comment by noloader** [comment]
Thanks @krichter722.

Forgive my ignorance... What problem would a release archive solve?

(Resetting the archive solves the problem of binary files distributed in `bootstrap` and clone/checkout bloat).

**Comment by krichter722** [comment]
There's no problem, it was just a hint to consider in the future. I'm not affected by the change. I'm not sure the change had any affect on the remote repository, though.

The release archive would not contain any history of `bootstrap/`, only the current state which should be all you need.
